#!/bin/sh


out_path="w_samples/"
ext01=".was"
ext02=".o"
o_path1="assembly/"
o_path2="object/"


path=$1

python vVc "$path"


name="${path##*/}"
name="${name%.*}"

output="${out_path}${o_path1}${name}${ext01}"



output2="${out_path}${o_path1}${name}${ext02}"

echo

echo "${out_path}${output}"
echo "${out_path}${output2}"
echo "${out_path}${name}"

nasm -f elf64 "$output" -l w_samples/tmp/lookup.txt


ld -o  "${out_path}${name}" "$output2"

